name: "Run recording automation"

on:
  schedule:
    - cron: "*/4 * * * *" # every 5 minutes
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run automation script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_HELLDIVERS_API_URL: ${{ secrets.NEXT_PUBLIC_HELLDIVERS_API_URL }}
        run: |
          echo "Attempt 1..."
          npx tsx -r dotenv/config src/scripts/recordState.ts || \
          (echo "Attempt 2 after 10s..." && sleep 30 && npx tsx -r dotenv/config src/scripts/recordState.ts) || \
          (echo "Attempt 3 after 30s..." && sleep 30 && npx tsx -r dotenv/config src/scripts/recordState.ts)
